# Generated by Django 4.2.2 on 2023-06-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='e', upload_to=''),
            preserve_default=False,
        ),
    ]
